# Site settings
title: You Blog                     #你博客的标题
header-img: static/zhouh.jpg     #显示在首页的背景图片
email: haozhou0806@gmail.com    
url: "https://zhouh.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
